version: '2'
services:
  elastics:
    image: 'elasticsearch:7.14.2'
    ports:
      - 9200:9200
    environment:
      - cluster.name=local-ek-stack

  kibana:
    image: 'kibana:7.14.2'
    depends_on:
      - 'elastic'
    environment:
      - elasticsearch.url=http://elasticsearch:9200
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
